### ISSUE TITLE
Out of memory error when running the quick start pre-trained model 

### ISSUE THREAD

**Issue by JamesAllingham** [facebookresearch/fairseq-lua#18]
I tried running the example for translating English to French:

`fairseq generate-lines -path wmt14.en-fr.fconv-cuda/model.th7 -sourcedict wmt14.en-fr.fconv-cuda/dict.en.th7 -targetdict wmt14.en-fr.fconv-cuda/dict.fr.th7 -beam 5`

However, the following error was given:

`| [target] Dictionary: 44666 types
| [source] Dictionary: 44409 types
THCudaCheck FAIL file=/home/james/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/james/torch/install/bin/luajit: /home/james/torch/install/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /home/james/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'read'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:351: in function </home/james/torch/install/share/lua/5.1/torch/File.lua:245>
	[C]: in function 'read'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/james/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/james/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...
	/home/james/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
	/home/james/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	.../install/share/lua/5.1/fairseq/models/ensemble_model.lua:32: in function '__init'
	/home/james/torch/install/share/lua/5.1/torch/init.lua:91: in function 'new'
	...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:153: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405d50
`

I tried reinstalling Torch  and fairseq as well as making sure that I have the most recent version of nn (`luarocks install nn`). Unfortunately none of these attempts fixed the problem.

The weird thing is that neither my 2 GB of GPU memory nor my 16 GB of RAM seemed to get remotely full before the error message appeared. 

Any help would be appreciated.

**Comment by jgehring** [comment]
Hi @JamesAllingham, I'm afraid that 2 GB of GPU memory are not enough to load or use this models. You could try the English-Romanian one which is a little smaller, but even then you will probably run out of memory during generation. We typically use GPUs with >10 GB of memory.

**Comment by michaelauli** [comment]
You could try the CPU version of the model instead. It is linked in the
README under "Pre-trained Models".

**Comment by JamesAllingham** [comment]
Thanks @jgehring, I ran it on a machine with 8GB of GPU memory and it worked like a charm. The CPU only version also worked on my laptop (thanks @michaelauli).

**Comment by shahbazsyed** [comment]
@jgehring @JamesAllingham  Is there a cmdline argument to specify the gpuid to use for loading the CUDA model for testing? I have 8 GPUs(8GB memory each) and 7 of them are in use by other process. I don't understand how the model is being loaded but it always gives me out of memory error after loading the dictionaries.

**Comment by jgehring** [comment]
No there is no such flag; I suggest using the [CUDA_VISIBLE_DEVICES](https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) environment variable to control which GPUs are available to the program.

**Comment by loretoparisi** [comment]
@JamesAllingham I have found that the issue was due to a `lua` process hanging - see here https://github.com/facebookresearch/fairseq/issues/31 I'm able to run GPU with 4gig.

**Comment by msiraj83** [comment]
I have the same error.... but my GPU is 2GB...Can i increase the GPU memory ???
