### ISSUE TITLE
cudnnutils.lua:13: You must have the torch Cudnn bindings.

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fairseq-lua#27]
I did

```
# Install CUDA libraries
RUN luarocks install torch && \
  luarocks install cutorch && \
  luarocks install cunn && \
  luarocks install cudnn
```

in a docker container with `torch` installed.

```
root@cf9f9a5a3f42:~/fairseq# fairseq generate-lines -path wmt14.en-fr.fconv-cuda/model.th7 -sourcedict wmt14.en-fr.fconv-cuda/dict.en.th7 -targetdict wmt14.en-fr.fconv-cuda/dict.fr.th7 -beam 5
Tried loading libnccl.so.1 but got error /root/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.so.1: cannot open shared object file: No such file or directory
Tried loading libnccl.1.dylib but got error /root/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.1.dylib: cannot open shared object file: No such file or directory
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/rnnlib/cudnnutils.lua:13: You must have the torch Cudnn bindings.
stack traceback:
	[C]: in function 'assert'
	/root/torch/install/share/lua/5.1/rnnlib/cudnnutils.lua:13: in main chunk
	[C]: in function 'require'
	...orch/install/share/lua/5.1/rnnlib/nn/WrappedCudnnRnn.lua:14: in main chunk
	[C]: in function 'require'
	/root/torch/install/share/lua/5.1/rnnlib/init.lua:18: in main chunk
	[C]: in function 'require'
	...h/install/share/lua/5.1/fairseq/models/avgpool_model.lua:18: in main chunk
	[C]: in function 'require'
	/root/torch/install/share/lua/5.1/fairseq/models/init.lua:15: in main chunk
	[C]: in function 'require'
	/root/torch/install/share/lua/5.1/fairseq/init.lua:14: in main chunk
	[C]: in function 'require'
	...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:15: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405d50
root@cf9f9a5a3f42:~/fairseq#
```

I have `cuDNN` installed:

```
root@cf9f9a5a3f42:~# luarocks install cudnn
Installing https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec... switching to 'build' mode
Cloning into 'cudnn.torch'...
remote: Counting objects: 60, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 60 (delta 15), reused 16 (delta 3), pack-reused 0
Receiving objects: 100% (60/60), 67.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (15/15), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/root/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/root/torch/install/lib/luarocks/rocks/cudnn/scm-1" && make

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /root/torch/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.0") 
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- CuDNN 5.1 not found at install-time. Please make sure it's in LD_LIBRARY_PATH at runtime
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cudnn-scm-1-8695/cudnn.torch/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialCrossEntropyCriterion.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialConvolution.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialBatchNormalization.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/BLSTM.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/LSTM.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/TemporalConvolution.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Pointwise.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/convert.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/ReLU.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/find.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialLogSoftMax.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialCrossMapLRN.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Pooling.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/ClippedReLU.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/ffi.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/LogSoftMax.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialMaxPooling.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Sigmoid.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialAveragePooling.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricLogSoftMax.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricBatchNormalization.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricMaxPooling.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/RNN.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricCrossEntropyCriterion.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/BGRU.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialDivisiveNormalization.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/RNNTanh.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/BatchNormalization.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SoftMax.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/env.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/functional.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialFullConvolution.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Tanh.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Pooling3D.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/RNNReLU.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricFullConvolution.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricConvolution.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/init.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialSoftMax.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricSoftMax.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricAveragePooling.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/GRU.lua
Updating manifest for /root/torch/install/lib/luarocks/rocks
cudnn scm-1 is now built and installed in /root/torch/install/ (license: BSD)
```

**Comment by loretoparisi** [comment]
My `LD_LIBRARY_PATH` is

```
root@cf9f9a5a3f42:~/fairseq# echo $LD_LIBRARY_PATH
/root/torch/install/lib:/root/torch/install/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

**Comment by jgehring** [comment]
Did you also install the actual [cuDNN library from NVidia](https://developer.nvidia.com/cudnn)? `cudnn` for Torch is just a wrapper for the NVidia one.

The install log you posted also hints at this:
> -- CuDNN 5.1 not found at install-time. Please make sure it's in LD_LIBRARY_PATH at runtime

**Comment by loretoparisi** [comment]
@jgehring ah so! This means  I should start from this docker image `nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04`, not the `nvidia/cuda:8.0-devel-ubuntu16.04`. Thanks I will try this.

**Comment by loretoparisi** [comment]
@jgehring  I have installed `nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04` that comes with `cdnn6` installed, but I'm still getting

```
root@05c251d3bd8d:~/fairseq# fairseq 
Usage: fairseq <tool> [options]
root@05c251d3bd8d:~/fairseq# fairseq generate-lines -path wmt14.en-fr.fconv-cuda/model.th7 -sourcedict wmt14.en-fr.fconv-cuda/dict.en.th7 -targetdict wmt14.en-fr.fconv-cuda/dict.fr.th7 -beam 5
Tried loading libnccl.so.1 but got error /root/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.so.1: cannot open shared object file: No such file or directory
Tried loading libnccl.1.dylib but got error /root/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.1.dylib: cannot open shared object file: No such file or directory
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/rnnlib/cudnnutils.lua:13: You must have the torch Cudnn bindings.
stack traceback:
	[C]: in function 'assert'
	/root/torch/install/share/lua/5.1/rnnlib/cudnnutils.lua:13: in main chunk
	[C]: in function 'require'
	...orch/install/share/lua/5.1/rnnlib/nn/WrappedCudnnRnn.lua:14: in main chunk
	[C]: in function 'require'
	/root/torch/install/share/lua/5.1/rnnlib/init.lua:18: in main chunk
	[C]: in function 'require'
	...h/install/share/lua/5.1/fairseq/models/avgpool_model.lua:18: in main chunk
	[C]: in function 'require'
	/root/torch/install/share/lua/5.1/fairseq/models/init.lua:15: in main chunk
	[C]: in function 'require'
	/root/torch/install/share/lua/5.1/fairseq/init.lua:14: in main chunk
	[C]: in function 'require'
	...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:15: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405d50
```

My env has 

```
LUA_PATH=/root/.luarocks/share/lua/5.1/?.lua;/root/.luarocks/share/lua/5.1/?/init.lua;/root/torch/install/share/lua/5.1/?.lua;/root/torch/install/share/lua/5.1/?/init.lua;./?.lua;/root/torch/install/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua
LUA_CPATH=/root/torch/install/lib/?.so;/root/.luarocks/lib/lua/5.1/?.so;/root/torch/install/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
CUDA_PKG_VERSION=8-0=8.0.61-1
CUDA_VERSION=8.0.61
DYLD_LIBRARY_PATH=/root/torch/install/lib:/root/torch/install/lib:
```

**Comment by jgehring** [comment]
What happens if you run this (from your shell): `th "require 'cudnn'"`?

**Comment by loretoparisi** [comment]
uhm I get

```
root@05c251d3bd8d:~/fairseq# th "require 'cudnn'"
/root/torch/install/bin/luajit: cannot open require 'cudnn': No such file or directory
stack traceback:
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

In the env I have also `CUDNN_VERSION=6.0.21`

**Comment by jgehring** [comment]
Argh, my bad! It should be `th -e "require 'cudnn'"`.

**Comment by loretoparisi** [comment]
```
root@05c251d3bd8d:~/fairseq# th -e "require 'cudnn'".
attempt to call a nil value
```

**Comment by jgehring** [comment]
Sorry, can you try it one last time without the dot?

**Comment by loretoparisi** [comment]
wops!!! 

```
root@05c251d3bd8d:~/fairseq# th -e "require 'cudnn'" 
/root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/cudnn/ffi.lua:1603: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in
your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

Alternatively, set the path to libcudnn.so.5 or libcudnn.5.dylib
to the environment variable CUDNN_PATH and rerun torch.
For example: export CUDNN_PATH = "/usr/local/cuda/lib64/libcudnn.so.5"
```

it seems files are not in place, or by default nvidia put somewhere else?

**Comment by loretoparisi** [comment]
this is what I get in `/usr/local/nvidia/lib64/lib`

```
root@05c251d3bd8d:~/fairseq# ls -l /usr/local/nvidia/lib64/lib
libEGL.so.1                          libGLESv2_nvidia.so.2                libcuda.so.1                         libnvidia-fatbinaryloader.so.367.57  libnvidia-opencl.so.1
libEGL_nvidia.so.0                   libGLESv2_nvidia.so.367.57           libcuda.so.367.57                    libnvidia-fbc.so.1                   libnvidia-opencl.so.367.57
libEGL_nvidia.so.367.57              libGLX.so.0                          libnvcuvid.so.1                      libnvidia-fbc.so.367.57              libnvidia-ptxjitcompiler.so.367.57
libGL.so.1                           libGLX_indirect.so.0                 libnvcuvid.so.367.57                 libnvidia-glcore.so.367.57           libnvidia-tls.so.367.57
libGL.so.1.0.0                       libGLX_nvidia.so.0                   libnvidia-compiler.so.367.57         libnvidia-glsi.so.367.57             libvdpau_nvidia.so.1
libGLESv1_CM.so.1                    libGLX_nvidia.so.367.57              libnvidia-egl-wayland.so.367.57      libnvidia-ifr.so.1                   libvdpau_nvidia.so.367.57
libGLESv1_CM_nvidia.so.1             libGLdispatch.so.0                   libnvidia-eglcore.so.367.57          libnvidia-ifr.so.367.57              
libGLESv1_CM_nvidia.so.367.57        libOpenGL.so.0                       libnvidia-encode.so.1                libnvidia-ml.so.1                    
libGLESv2.so.2                       libcuda.so                           libnvidia-encode.so.367.57           libnvidia-ml.so.367.57
```

and

```
root@05c251d3bd8d:~/fairseq# ls -l /usr/local/cuda/lib64/
libOpenCL.so                 libcufft.so                  libcurand_static.a           libnppi.so.8.0.61            libnppif.so.8.0              libnppitc.so.8.0             libnvgraph.so.8.0.61
libOpenCL.so.1               libcufft.so.8.0              libcusolver.so               libnppi_static.a             libnppif.so.8.0.61           libnppitc.so.8.0.61          libnvgraph_static.a
libOpenCL.so.1.0             libcufft.so.8.0.61           libcusolver.so.8.0           libnppial.so                 libnppig.so                  libnpps.so                   libnvrtc-builtins.so
libOpenCL.so.1.0.0           libcufft_static.a            libcusolver.so.8.0.61        libnppial.so.8.0             libnppig.so.8.0              libnpps.so.8.0               libnvrtc-builtins.so.8.0
libcublas.so                 libcufftw.so                 libcusolver_static.a         libnppial.so.8.0.61          libnppig.so.8.0.61           libnpps.so.8.0.61            libnvrtc-builtins.so.8.0.61
libcublas.so.8.0             libcufftw.so.8.0             libcusparse.so               libnppicc.so                 libnppim.so                  libnpps_static.a             libnvrtc.so
libcublas.so.8.0.61          libcufftw.so.8.0.61          libcusparse.so.8.0           libnppicc.so.8.0             libnppim.so.8.0              libnvToolsExt.so             libnvrtc.so.8.0
libcublas.so.8.0.71          libcufftw_static.a           libcusparse.so.8.0.61        libnppicc.so.8.0.61          libnppim.so.8.0.61           libnvToolsExt.so.1           libnvrtc.so.8.0.61
libcublas_device.a           libcuinj64.so                libcusparse_static.a         libnppicom.so                libnppist.so                 libnvToolsExt.so.1.0.0       stubs/
libcublas_static.a           libcuinj64.so.8.0            libnppc.so                   libnppicom.so.8.0            libnppist.so.8.0             libnvblas.so                 
libcudadevrt.a               libcuinj64.so.8.0.61         libnppc.so.8.0               libnppicom.so.8.0.61         libnppist.so.8.0.61          libnvblas.so.8.0             
libcudart.so                 libculibos.a                 libnppc.so.8.0.61            libnppidei.so                libnppisu.so                 libnvblas.so.8.0.61          
libcudart.so.8.0             libcurand.so                 libnppc_static.a             libnppidei.so.8.0            libnppisu.so.8.0             libnvblas.so.8.0.71          
libcudart.so.8.0.61          libcurand.so.8.0             libnppi.so                   libnppidei.so.8.0.61         libnppisu.so.8.0.61          libnvgraph.so                
libcudart_static.a           libcurand.so.8.0.61          libnppi.so.8.0               libnppif.so                  libnppitc.so                 libnvgraph.so.8.0
```

**Comment by jgehring** [comment]
Is cudnn somewhere else in /usr maybe? If you have cuDNN6, you may need to install the R6 branch of cudnn, i.e.:

```
$ git clone https://github.com/soumith/cudnn.torch
$ cd cudnn.torch
$ git checkout origin/R6
$ luarocks make cudnn-scm-1.rockspec
```

**Comment by loretoparisi** [comment]
@jgehring Yay! thank you! It now loads, but it still has some path issue, this time with `ffi`

```
root@05c251d3bd8d:~/fairseq# fairseq generate-lines -path wmt14.en-fr.fconv-cuda/model.th7 -sourcedict wmt14.en-fr.fconv-cuda/dict.en.th7 -targetdict wmt14.en-fr.fconv-cuda/dict.fr.th7 -beam 5
Tried loading libnccl.so.1 but got error /root/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.so.1: cannot open shared object file: No such file or directory
Tried loading libnccl.1.dylib but got error /root/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.1.dylib: cannot open shared object file: No such file or directory
| [target] Dictionary: 44666 types
| [source] Dictionary: 44409 types
> hello world!
/root/torch/install/bin/luajit: ...rch/install/share/lua/5.1/fairseq/models/fconv_model.lua:84: attempt to index field 'weight' (a nil value)
stack traceback:
	...rch/install/share/lua/5.1/fairseq/models/fconv_model.lua:84: in function 'onEvaluate'
	...install/share/lua/5.1/fairseq/modules/TrainTestLayer.lua:29: in function 'evaluate'
	/root/torch/install/share/lua/5.1/nn/Container.lua:91: in function 'func'
	/root/torch/install/share/lua/5.1/nn/Container.lua:73: in function 'applyToModules'
	/root/torch/install/share/lua/5.1/nn/Container.lua:91: in function 'evaluate'
	/root/torch/install/share/lua/5.1/nn/Container.lua:91: in function 'func'
	/root/torch/install/share/lua/5.1/nn/Container.lua:73: in function 'applyToModules'
	/root/torch/install/share/lua/5.1/nn/Container.lua:91: in function 'evaluate'
	/root/torch/install/share/lua/5.1/nn/Container.lua:91: in function 'func'
	/root/torch/install/share/lua/5.1/nn/Container.lua:73: in function 'applyToModules'
	/root/torch/install/share/lua/5.1/nn/Container.lua:91: in function 'evaluate'
	/root/torch/install/share/lua/5.1/nn/Container.lua:91: in function 'func'
	/root/torch/install/share/lua/5.1/nn/Container.lua:73: in function 'applyToModules'
	/root/torch/install/share/lua/5.1/nn/Container.lua:91: in function 'evaluate'
	...rch/install/share/lua/5.1/fairseq/models/fconv_model.lua:652: in function 'setup'
	.../install/share/lua/5.1/fairseq/models/ensemble_model.lua:102: in function 'generate'
	...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:218: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405d50
root@05c251d3bd8d:~/fairseq# 
```

**Comment by jgehring** [comment]
You're still missing [NCCL](https://github.com/NVIDIA/nccl) and likely have an outdated version of `nn` (fairseq needs a version that is more recent than the one shipped with torch/distro). You can fix the latter with `luarocks install nn`.

**Comment by loretoparisi** [comment]
@jgehring right, thanks, going to install `nccll` via git since the docker image does not have it and adding the update of `nn`. Hopefully it will work then, update soon.

**Comment by loretoparisi** [comment]
@jgehring So it seems I did a step forward 👍 

```
root@7ba08c929730:~/fairseq# fairseq generate-lines -path wmt14.en-fr.fconv-cuda/model.th7 -sourcedict wmt14.en-fr.fconv-cuda/dict.en.th7 -targetdict wmt14.en-fr.fconv-cuda/dict.fr.th7 -beam 5
| [target] Dictionary: 44666 types
| [source] Dictionary: 44409 types
> Hello world!
S	<unk> <unk> 
O	Hello world!
H	-1.1125671863556	faul@@ ty time 
A	1 2 2 3
> 
```

or

```
> Why is it rare to discover new marine mam@@ mal species ?
S	Why is it rare to discover new marine mam@@ mal species ? 
O	Why is it rare to discover new marine mam@@ mal species ?
H	-0.068684287369251	Pourquoi est-il rare de découvrir de nouvelles espèces de mammifères marins ? 
A	1 1 4 4 6 6 7 11 9 9 9 12 13
>
```

Question: what does it mean `faul@@ ty time ` ? Is that related to the `<unk>` tag i.e. `unknown` I suppose...

**Comment by michaelauli** [comment]
'@@' marks a BPE token. You can remove the BPE segmentation by running sed
's/@@ //g' on the output of the model.
 You should also make sure that the data you provide to the model is
properly tokenized and BPE segmented. We used the the Moses tokenizer for
the former and the bpecodes file is in the model archive.

**Comment by riteshpanjwani** [comment]
@jgehring I get the same error as above when I run:

`fairseq preprocess -sourcelang de -targetlang en   -trainpref $TEXT/train -validpref $TEXT/valid -testpref $TEXT/test   -thresholdsrc 3 -thresholdtgt 3 -destdir data-bin/iwslt14.tokenized.de-en`


`THCudaCheck FAIL file=/home/development/riteshp/torch/extra/cutorch/init.c line=778 error=2 : out of memory
/home/development/riteshp/torch/install/bin/lua: ...iteshp/torch/install/share/lua/5.2/rnnlib/cudnnutils.lua:13: You must have the torch Cudnn bindings.
stack traceback:
	[C]: in function 'assert'
	...iteshp/torch/install/share/lua/5.2/rnnlib/cudnnutils.lua:13: in main chunk
	[C]: in function 'require'
	...orch/install/share/lua/5.2/rnnlib/nn/WrappedCudnnRnn.lua:14: in main chunk
	[C]: in function 'require'
	...ment/riteshp/torch/install/share/lua/5.2/rnnlib/init.lua:18: in main chunk
	[C]: in function 'require'
	...h/install/share/lua/5.2/fairseq/models/avgpool_model.lua:18: in main chunk
	[C]: in function 'require'
	...eshp/torch/install/share/lua/5.2/fairseq/models/init.lua:15: in main chunk
	[C]: in function 'require'
	...ent/riteshp/torch/install/share/lua/5.2/fairseq/init.lua:14: in main chunk
	[C]: in function 'require'
	...rch/install/share/lua/5.2/fairseq/scripts/preprocess.lua:44: in main chunk
	[C]: in function 'require'
	...install/lib/luarocks/rocks/fairseq-cpu/scm-1/bin/fairseq:17: in main chunk
	[C]: in ?`

My CUDA version is 7.5
I have already installed the following:

- CuDNN 5.1 by Nvidia

- Torch cudnn binding (and it is able to find CuDNN 5.1, no error over there)

- latest version of nn package & NCCL library. 


This is how LD_LIBRARY_PATH looks like:

`:/home/development/riteshp/torch/install/lib:/usr/local/cuda/lib64:/usr/local/nccl/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/include`


I also ran `th -e "require 'cudnn'"` and got the following output:

`THCudaCheck FAIL file=/home/development/riteshp/torch/extra/cutorch/init.c line=778 error=2 : out of memory
...pment/riteshp/torch/install/share/lua/5.2/trepl/init.lua:389: ...pment/riteshp/torch/install/share/lua/5.2/trepl/init.lua:389: ...opment/riteshp/torch/install/share/lua/5.2/cudnn/ffi.lua:1624: cuda runtime error (2) : out of memory at /home/development/riteshp/torch/extra/cutorch/init.c:77`

**Comment by loretoparisi** [comment]
@riteshpanjwani I strongly suggest you to move to `docker`. This installation is very complex and time wasting!

**Comment by riteshpanjwani** [comment]
@loretoparisi Sorry, but I am not familiar with 'docker' Can you please tell me the advantages of moving to `docker` ?

**Comment by loretoparisi** [comment]
read [here](https://docs.docker.com/get-started/) first to have an overview and to easily create the first docker container up and running in few minutes!

**Comment by riteshpanjwani** [comment]
@loretoparisi @jgehring I was able to solve this issue by selecting other GPU using `export CUDA_VISIBLE_DEVICES=3` which was free. By default, it was using the first GPU which didn't have enough memory. Anyway, thanks for the help.
