### ISSUE TITLE
CUDA error  "Assertion `srcIndex < srcSelectDimSize` failed"

### ISSUE THREAD

**Issue by matthias-samwald** [facebookresearch/fairseq-lua#57]
I'm scratching my head over a CUDA error that occurred while training (CUDA version 8.0). I did not encounter this error while training on the IWSLT14 German-English corpus as described in the tutorial, so perhaps this is triggered by some property of the training files?

> fairseq train -sourcelang source -targetlang target -datadir fairseq-data-bin/simple-wikipedia-autoencoder -model fconv -nenclayer 4 -nlayer 3 -dropout 0.2 -optim nag -lr 0.25 -clip 0.1 -momentum 0.99 -timeavg -bptt 0 -savedir fairseq-fconv-model 
| [target] Dictionary: 18961 types
| [source] Dictionary: 16324 types
| IndexedDataset: loaded fairseq-data-bin/simple-wikipedia-autoencoder with 5238230 examples
| IndexedDataset: loaded fairseq-data-bin/simple-wikipedia-autoencoder with 291010 examples
| IndexedDataset: loaded fairseq-data-bin/simple-wikipedia-autoencoder with 291010 examples
| IndexedDataset: loaded fairseq-data-bin/simple-wikipedia-autoencoder with 291010 examples
| IndexedDataset: loaded fairseq-data-bin/simple-wikipedia-autoencoder with 291010 examples
| epoch 000 | 0001000 updates | words/s   16573| trainloss     5.45 | train ppl    43.58
[MANY LINES OMITTED]
| epoch 000 | 0016000 updates | words/s   18023| trainloss     1.39 | train ppl     2.62
/home/matthias/torch/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [43,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/matthias/torch/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [43,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/matthias/torch/extra/cutorch/lib/THC/THCTensorIndex.cu:321: void 
indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [42,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[MANY LINES OMITTED]
THCudaCheck FAIL file=/home/matthias/torch/extra/cutorch/lib/THC/generic/THCTensorCopy.c line=18 error=59 : device-side assert triggered
/home/matthias/torch/install/bin/luajit: ...matthias/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] /home/matthias/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
/home/matthias/torch/install/share/lua/5.1/nn/Bottle.lua:22: cuda runtime error (59) : device-side assert triggered at /home/matthias/torch/extra/cutorch/lib/THC/generic/THCTensorCopy.c:18
stack traceback:
	[C]: in function 'copy'
	/home/matthias/torch/install/share/lua/5.1/nn/Bottle.lua:22: in function </home/matthias/torch/install/share/lua/5.1/nn/Bottle.lua:14>
	[C]: in function 'xpcall'
	/home/matthias/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...e/matthias/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	...matthias/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...matthias/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'func'
	...matthias/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...matthias/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:356: in function <...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:333>
	[C]: in function 'xpcall'
	...matthias/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	...e/matthias/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...e/matthias/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	...e/matthias/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
> WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/matthias/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	...e/matthias/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	...matthias/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...matthias/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'func'
	...matthias/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...matthias/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:356: in function <...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:333>
	[C]: in function 'xpcall'
	...matthias/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	...e/matthias/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...e/matthias/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	...e/matthias/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	...matthias/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	...matthias/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
	...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:371: in function 'doTrain'
	...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:189: in function 'train'
	...as/torch/install/share/lua/5.1/fairseq/scripts/train.lua:405: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405d50

Full error message at https://gist.github.com/matthias-samwald/21d614dd663cc10c7ebb0f23ce8f61c5

**Comment by jgehring** [comment]
@matthias-samwald can you re-run this with the `CUDA_LAUNCH_BLOCKING` environment variable set to 1? This way, you should get a trace pointing to the actual origin of the error.

**Comment by matthias-samwald** [comment]
@jgehring  Sure. Here is the error message with CUDA_LAUNCH_BLOCKING=1:
https://gist.github.com/matthias-samwald/a69a569dd1a8cc1deaffc42934a90283

**Comment by jgehring** [comment]
Thanks! I still don't fully understand what's happening, though. Could it be that you have fairly long sentences in your training data, i.e. longer than 1024 tokens? That's a hard-coded limit right now for the positional embeddings lookup table.

**Comment by matthias-samwald** [comment]
Indeed I found a few sentences exceeding that length. The problem was solved by limiting sentence size in the training files. Thanks for the swift reply!

**Comment by sheerun** [comment]
I also had this issue. Is 1024 limit really necessary?

**Comment by happygirl123456** [comment]
hello ,after I use BPE, I met the same issue ,but I don't konw how to limit sentence size in the training files. could you give me some help,Thanks! @jgehring

**Comment by michaelauli** [comment]
@sheerun: you can change it, just look for 1024 in the code. Alternatively, filter the input sequence pairs (https://github.com/facebookresearch/fairseq/issues/81#issuecomment-329278528).

**Comment by chandra-siri** [comment]
@michaelauli can we simply change the default value of --max-source-positions from 1024 to something higher instead of changing the code ?
