### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fairseq-lua#62]
I get this error when executing on `Ubuntu 16.04LTS` with cuda:

```
exec:fairseq stderr:THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-2979/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version
```

This is confirmed when trying to run `torch` directly:

```
root@2b519efce6eb:/musixmatch# th -e "require 'cutorch'"
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-2979/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version
/mxmlib/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-2979/cutorch/lib/THC/THCGeneral.c:66
```

and after this (and I suppose due to this issue) I get several `not found` like

```
exec:fairseq stderr:tput: No value for $TERM and no -T specified

not found: TemporalConvolutionTBC_updateOutput_Cuda
not found: TemporalConvolutionTBC_updateGradInput_Cuda
not found: TemporalConvolutionTBC_accGradParameters_Cuda
not found: TemporalConvolutionTBC_updateOutput_CudaDouble
not found: TemporalConvolutionTBC_updateGradInput_CudaDouble
not found: TemporalConvolutionTBC_accGradParameters_CudaDouble
...
```

I have

```
10.0.90.190 ubuntu@ai-tools-nmt-i-04fc6623dcd3531f8:~$ nvidia-smi
Tue Jun 20 15:53:43 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   30C    P8    17W / 125W |      0MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

My install scripts are [here](https://github.com/loretoparisi/docker/blob/master/fairseq/Dockerfile), the installation of all libraries works fine.

To note that I'm not loading a GPU model, but a CPU one:

```javascript
[ 'generate-lines',
  '-path',
  '/root/nmt/wmt14.en-de.fconv-float/model.th7',
  '-sourcedict',
  '/root/nmt/wmt14.en-de.fconv-float/dict.en.th7',
  '-targetdict',
  '/root/nmt/wmt14.en-de.fconv-float/dict.de.th7',
  '-beam',
  '5',
  '-input',
  '-' ]
```

This works ok on `macOS` CPU.

**Comment by nikefd** [comment]
Hi, @loretoparisi , I met the same problem as you. I don't know why this happen. 
But I solved it by reconfigure environment.
Following is my configuration procedure.

I used windows 10 and docker set as Linux containers. 
At first, I pull a image including cuda and install torch myself. I met the same problem as you.
So I reconfigure environment
`docker pull kaixhin/torch`
And I found the version of torch is too low. So I updated it.
```
luarocks install torch
luarocks install nn
luarocks make rocks/fairseq-cpu-scm-1.rockspec    //**cpu**
```
Finally I loading a cpu model that is generated in a gpu environment and everything work well.
Hope this is helpful to you.

**Comment by loretoparisi** [comment]
@nikefd thank you!

**Comment by jgehring** [comment]
Looks like this has been resolved; closing.

**Comment by brando90** [comment]
does someone know how to solve this for pytorch?
